/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111510-gbe7ac511a6-20230719"
#endif /* AVUTIL_FFVERSION_H */
